language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
  - "4"
  - "6"
before_script:
  - ./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - ./node_modules/.bin/jspm install
script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
env:
  global:
    secure: A0wzEkoPBcUZVKIN7rKm2sEza+jyikbJ+J33i+fzWV/hXHkCS8Eg/KznPcc3NFkI1fwImXhweZab4PRcbmJduNoMOXMLULUVH6XrhXPDaKspMRm5/gOs4R3+uKkzelpoCsTsd6R+U8BIw54To/WzjLwVuXB4N/1Mofwt/r5kJO1WLesbh14j5I1bLpaeWjBPu3sMA0bwuoLKimlBnHXbHVDo8g825KjTa9dyqTIHgSwZLp+I3HDjVWfgVlat91YfplPRwMLHYgrADwBxVAI4H15YMzmosREHtQrt1J6uGTHy278STR9vsN8Xl9z93ryVTOqO6UMFC+ccejvjVUpt1OnJDUeYhywZXE6BHmwJeEvJqVeNks1TGJVHqoGLraEZMHLWcUJFSIqhPRGQE3hlAMvvwIrrYtQIn8bB/QqYpieyWnfDkGYwKSijWci94zcmvyo4OqfbrXvvkIkIw5FFH8Ma3LHr/ewRNdiReL9iX85f4D9sih7jfpZNOmf2rZ2h7g8ZNhXs90wD9oFwST7tq/6PgLUuObqmIwsyQ3iGqhja6KwMcKcKFtVg0J51oRH4C8VGOy1G5sOetBhCz8IbEaN1uPkOCAjHRiizx2NtS2HXB0scq84Jlhpmz5eKrdojVy2Ujz0S+FrmVl8RsX4FlIYL20ldx/+d72ah1RlHqsQ= #JSPM_GITHUB_AUTH_TOKEN
