language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "4"
  - "6"
script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
